### ISSUE TITLE
求使用教程

### ISSUE THREAD

**Issue by RookieTerry** [bclswl0827/Fuck-ChaoXing#1]
请问具体怎么使用？是在视频播放页面打开f12控制台，再粘贴js代码吗？

**Comment by bclswl0827** [comment]
Nope, use Tampermonkey instead.

**Comment by RookieTerry** [comment]
在油猴脚本里面粘贴吗？

**Comment by bclswl0827** [comment]
Both cpoy & paste and Import from the control panel are available.
