### ISSUE TITLE
OCR识别不出来

### ISSUE THREAD

**Issue by Weihong-Liu** [bclswl0827/Fuck-ChaoXing#2]
![image](https://user-images.githubusercontent.com/65588374/168003390-fd0edeca-e7ea-46e1-baa8-ad229e973f9a.png)
报以上错误

**Comment by bclswl0827** [comment]
挂上梯子试试，Tesseract.js 会从国外拉取两个模型文件，挺大的

**Comment by bclswl0827** [comment]
你好，模型文件的 URL 已经替换到我自己的服务器上了，你可以重新安装新版本再试
