### ISSUE TITLE
答题卡住

### ISSUE THREAD

**Issue by NullKioo** [bclswl0827/Fuck-ChaoXing#3]
![image](https://user-images.githubusercontent.com/67960720/168500899-2eb1d127-5ade-4d60-8fa1-6152c8960731.png)一直卡在这里

**Comment by NullKioo** [comment]
![image](https://user-images.githubusercontent.com/67960720/168501045-047cb316-f44b-43fe-a8a8-6fafc89d10da.png)
当前进度满之后，就不再继续

**Comment by bclswl0827** [comment]
能附上控制台的截图吗，另，这套脚本貌似不适合拿来做英文题目，不过后续可能会改进

**Comment by NullKioo** [comment]
![image](https://user-images.githubusercontent.com/67960720/168504635-8349897b-2e3a-4184-a1fd-6043a93ef8e6.png)

**Comment by 1955782864** [comment]
![image](https://user-images.githubusercontent.com/67960720/168504751-2682789b-2b04-4bdc-b3b0-0b4eecb63f46.png)
zh这种情况下不进行答题，也有可能我做的是英语作业

**Comment by bclswl0827** [comment]
> ![image](https://user-images.githubusercontent.com/67960720/168501045-047cb316-f44b-43fe-a8a8-6fafc89d10da.png) 当前进度满之后，就不再继续

图片太多了，超过 setTimeout 设定的等待将 DOM 转成 base64 时间了，后续会尝试修复

**Comment by NullKioo** [comment]
好


---原始邮件---
发件人: &quot;Yuki ***@***.***&gt;
发送时间: 2022年5月16日(周一) 中午11:56
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [bclswl0827/Fuck-ChaoXing] 答题卡住 (Issue #3)




  
 当前进度满之后，就不再继续
  
图片太多了，超过 setTimeout 设定的等待将 DOM 转成 base64 时间了，后续会尝试修复
 
&mdash;

**Comment by bclswl0827** [comment]
你好，貌似纯英文的题目是不会有加密的，你可以关掉脚本试试

**Comment by NullKioo** [comment]
有些会有中文夹在里面


---原始邮件---
发件人: &quot;Yuki ***@***.***&gt;
发送时间: 2022年5月16日(周一) 中午12:20
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [bclswl0827/Fuck-ChaoXing] 答题卡住 (Issue #3)




 
你好，貌似纯英文的题目是不会有加密的，你可以关掉脚本试试
 
&mdash;
